print ("arithmetic operations")
A=input ("enter number:")
print ("A=",A)
B=input ("enter second number:")
print ("B=", B)
C=input ("enter third number:")
print ("C=", C)
D=input ("enter fourth number:")
print ("D=", D)
E=input ("enter fifth number:")
print ("E=", E) 
F=input ("enter sixth number:")
print ("F=", F)
A=int(A)
B=int(B)
C=int(C)
D=int(D)
E=int(E)
F=int(F)
print ("Add", (A+B))
print ("Subtract", (D-C))
print ("Multiply", (B*D))
print ("Divide", (F/C, F%C))
