print("Calculate your total here")
bill=input("Enter bill:")
bill=float(bill)
print("Choose your tip")
tipa=(bill*.1)
print("10%:", "tip",tipa, "total",(tipa+bill))
tipb=(bill*.15)
print("15%:", "tip",tipb, "total",(tipb+bill))
tipc=(bill*.2)
print("20%:", "tip",tipc, "total",(tipc+bill))
tipd=(bill*.25)
print("25%:", "tip",tipd, "total",(tipd+bill))
print("Or choose desired tip")
percent=input("Enter percent as a decimal:")
percent=float(percent)
Tip=(percent*bill)
print("Tip:", Tip, "Total:", Tip+bill)  