bill=47.56
tipa=(bill*.1)
totala=tipa+bill
print("bill",bill)
print ("tip 10%", tipa)
print ("total", totala)
tipb=(bill*.15)
totalb=(bill+tipb)
print("tip 15%", tipb)
print ("total", totalb)
tipc=(bill*.2)
totalc=(bill+tipc)
print("tip 20%", tipc)
print("total", totalc)
tipd=(bill*.25)
totald=(bill+tipd)
print ("tip 25%", tipd)
print("total", totald)
print("problem 7")
print("calculate pay")
pay=input("Hourly rate:")
pay=float(pay)
hrs=input("Hours worked:")
hrs=float(hrs)
print("Pay: $", pay*hrs)